apiVersion: v1
kind: Service
metadata:
  namespace: http-app
  name: http-service
  labels:
    app: http-app
spec:
  selector:
    app: http-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80